SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS ri
JOIN REST_REVIEW AS rr ON ri.REST_ID = rr.REST_ID
WHERE LEFT(ri.ADDRESS, 2) = '서울'
GROUP BY rr.REST_ID
ORDER BY SCORE DESC, ri.FAVORITES DESC;